### ISSUE TITLE
[feature] support rolling update

### ISSUE THREAD

**Issue by zhyass** [radondb/radondb-mysql-kubernetes#121]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Upgrade the follower nodes first, and then upgrade the leader node last. 

For a two-node cluster, we need to adjust the parameter rpl_semi_sync_master_timeout before upgrading from the node. Otherwise, the leader node will hang due to semi-sync.

**Describe alternatives you've considered**

**Additional context**

Reference: [Qingcloud MySQL Plus](https://docs.qingcloud.com/product/database_cache/app_mysql_plus/index.html)

**Comment by zhyass** [comment]
update the configmap:

https://www.robustperception.io/reloading-prometheus-configuration

https://stackoverflow.com/questions/37317003/restart-pods-when-configmap-updates-in-kubernetes

**Comment by zhyass** [comment]
https://www.cnblogs.com/sanduzxcvbnm/p/13084064.html

**Comment by zhyass** [comment]
https://kubernetes.io/zh/docs/reference/using-api/api-concepts/

**Comment by zhyass** [comment]
TODO: support two-node cluster

**Comment by zhyass** [comment]
`rpl_semi_sync_master_timeout` has been setted by xenon when the replica is 2, we need not set again.

**Comment by andyli029** [comment]
ACK
