### ISSUE TITLE
[feature] create crd when install operator.

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#150]
**Is your feature request related to a problem? Please describe.**

Take backup as an example：

`clusters.mysql.radondb.com` crd can automatically installed, but need install `backups.mysql.radondb.com` CRD manually.
operator helm: https://github.com/radondb/radondb-mysql-kubernetes/tree/main/charts

**Describe the solution you'd like**

install `clusters.mysql.radondb.com` and `backups.mysql.radondb.com` when install operator 

- add `mysql.radondb.com_backups.yaml` to `charts/mysql-operator/crds/`
- update `mysql.radondb.com_clusters.yaml`
- modify `charts/mysql-operator/templates/cluster_rbac.yaml`

**Describe alternatives you've considered**

**Additional context**

**Comment by andyli029** [comment]
#144
