### ISSUE TITLE
[documentation] update deploy operator docs

### ISSUE THREAD

**Issue by hustjieke** [radondb/radondb-mysql-kubernetes#152]
**Is your feature request related to a problem? Please describe.**

[N/A]

**Describe the solution you'd like**

[N/A]

**Describe alternatives you've considered**

[N/A]

**Additional context**

[N/A]

**Comment by runkecheng** [comment]
deployment have some changes , see #144 
i will update deployment doc and #151 together

**Comment by Lydialin2390** [comment]
ACK
