### ISSUE TITLE
when the status not update， change replicas and apply the mysql_v1alpha1_cluster.yaml , happen nothing

### ISSUE THREAD

**Issue by acekingke** [radondb/radondb-mysql-kubernetes#158]
**Describe the problem**

**To Reproduce**

1. repliacs in yaml is 3, `kubectl apply -f config/samples/mysql_v1alpha1_cluster.yaml` , it can sucess
2. change replicas to 2 then  `kubectl apply -f config/samples/mysql_v1alpha1_cluster.yaml`, it can success
3. Don't wait all pod status change, change replicas to 3 or 5, `kubectl apply -f config/samples/mysql_v1alpha1_cluster.yaml`, it will still in 2 pods , never change to 3 or 5.

**Expected behavior**
```
func (s *StatefulSetSyncer) updatePod(ctx context.Context) error {
	if s.sfs.Status.UpdatedReplicas >= s.sfs.Status.Replicas {
		return nil
	}

	log.Info("statefulSet was changed, run update")

	if s.sfs.Status.ReadyReplicas < s.sfs.Status.Replicas {
		log.Info("can't start/continue 'update': waiting for all replicas are ready")
		return nil  //<---- code here is uncorrect, should return error
	}
```

**Environment:**

- RadonDB MySQL version:

**Comment by andyli029** [comment]
Ping @runkecheng

**Comment by acekingke** [comment]
fix it in https://github.com/radondb/radondb-mysql-kubernetes/pull/161

**Comment by andyli029** [comment]
> fix it in #161

need fix it again.

**Comment by acekingke** [comment]
when 3 --> 2 ,  2 pods just update one status, and the status is running, change it 3 quickly, it still will fail

**Comment by acekingke** [comment]
when 3 --> 2 , `pod 0, pod 1 `will  delete then create, but `pod 2` will never create again, the logic will retry it for 2 hours, during the time ,reconsile cannot do anything, so it will happend nothing for yaml changed
