### ISSUE TITLE
[feature] Add ServiceMonitor for operator

### ISSUE THREAD

**Issue by zhyass** [radondb/radondb-mysql-kubernetes#169]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

reference:

https://github.com/radondb/radondb-mysql-kubernetes/blob/main/charts/helm/templates/servicemonitor.yaml

**Describe alternatives you've considered**

**Additional context**

**Comment by runkecheng** [comment]
The name of the monitoring service is <releaseName>-metrics, for example, if you create a cluster called `sample-mysql`, the monitoring service name is `sample-metrics`
