### ISSUE TITLE
[Feature] support MySQL 8.0

### ISSUE THREAD

**Issue by acekingke** [radondb/radondb-mysql-kubernetes#176]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Support MySQL 8.0 

**Describe alternatives you've considered**

**Additional context**

Mysql 8.0 create user do not like Mysql 5.7 , and so on

**Comment by acekingke** [comment]
my.cnf changes : `query_cache_size` do not exist

**Comment by acekingke** [comment]
Cannot set 
	"plugin-load":                        "\"semisync_master.so;semisync_slave.so;audit_log.so;connection_control.so\"",
in my.cnf when initializer
```
2021-08-16T09:58:35.009228-00:00 0 [Warning] [MY-013501] [Server] Ignoring --plugin-load[_add] list as the server is running with --initialize(-insecure).
```

**Comment by andyli029** [comment]
ACK.

**Comment by acekingke** [comment]
GRANT ALL ON *.* TO 'root'@'127.0.0.1' IDENTIFIED BY '%s' with grant option; 
Is not support by mysql8
should use `create user` then `grant`

**Comment by acekingke** [comment]
the percona-server 8.0 	 has bug
		ps-admin --docker --enable-tokudb -u root -p $MYSQL_ROOT_PASSWORD
will promot to enter the password 
![image](https://user-images.githubusercontent.com/7586502/129847774-739f5a96-504a-4de0-8ec1-b319d3f5f1e6.png)

**Comment by acekingke** [comment]
Impletement scheme:
1. change `grant  `sql to `create user` sql and `grant` sql
2. Cannot install plugin in initializer, so, create special.cnf with plugin configurations in pecona-server post run script , after initializer, run shell to copy special.cnf to conf.d

**Comment by andyli029** [comment]
Link：https://github.com/radondb/radondb-mysql-kubernetes/pull/196#issuecomment-1085639003

**Comment by acekingke** [comment]
@andyli029  https://github.com/radondb/radondb-mysql-kubernetes/pull/196#issuecomment-1085639003 has been dealt with
