### ISSUE TITLE
[doc] Change the related name of qingcloud to the name related to radondb.

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#191]
**Is your feature request related to a problem? Please describe.**

Avoid qingcloud as much as possible in the naming of the product.

**Describe the solution you'd like**

Change the related name of **qingcloud** to the name related to **radondb**.

Need to think of a suitable name, not too long.

**Describe alternatives you've considered**

**Additional context**

I will complete the modification of the code part, the documentation part is troublesome @molliezhang  and @KID-G  to complete.

**Comment by molliezhang** [comment]
How about  use  **radondb**？ the default  password **radondb#1234** ？

@KID-G @runkecheng @andyli029

**Comment by molliezhang** [comment]
qc --> radondb or rdb

**Comment by acekingke** [comment]
ok

**Comment by acekingke** [comment]
Qing@123 --> RadonDB@123
qc_ --> rdb_
qingcloud-->radondb
