### ISSUE TITLE
[bug] if backup Job is completed or error, crd do not remove the old backup job

### ISSUE THREAD

**Issue by acekingke** [radondb/radondb-mysql-kubernetes#193]
**Describe the problem**
if backup Job is completed or error, crd do not remove the old backup job

**To Reproduce**

1.

**Expected behavior**

**Environment:**

- RadonDB MySQL version:

**Comment by andyli029** [comment]
![21641629708580_ pic_hd](https://user-images.githubusercontent.com/15212006/130546129-ff5d6f2a-3899-4250-869d-30180b017fb3.jpg)

**Comment by andyli029** [comment]
#144
