### ISSUE TITLE
[feature] fix 5.7.33 to 5.7.34 

### ISSUE THREAD

**Issue by hustjieke** [radondb/radondb-mysql-kubernetes#200]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

```
cluster/container/init_sidecar_test.go:104:			Value: "5.7.33",
cluster/container/mysql_test.go:55:	assert.Equal(t, "percona/percona-server:5.7.33", mysqlCase.Image)
cluster/container/init_mysql_test.go:108:	assert.Equal(t, "percona/percona-server:5.7.33", initMysqlCase.Image)
docs/others/setup-rw-svc.md:74:Server version: 5.7.33-36-log Percona Server (GPL), Release '36', Revision '7e403c5'
utils/constants.go:21:	MySQLDefaultVersion = "5.7.33"
utils/constants.go:25:		"5.7": "5.7.33",
utils/constants.go:30:		"5.7.33": "percona/percona-server:5.7.33",
```

**Additional context**

releated to https://github.com/radondb/radondb-mysql-kubernetes/pull/123

**Comment by zhyass** [comment]
In https://github.com/radondb/radondb-mysql-kubernetes/blob/main/utils/constants.go#L30 we have a list of the support version, such as 5.7.33, 5.7.34.  
Reference: https://github.com/bitpoke/mysql-operator/blob/master/pkg/util/constants/constants.go#L94
