### ISSUE TITLE
[Bug] Xenon postStart script loop forever 

### ISSUE THREAD

**Issue by acekingke** [radondb/radondb-mysql-kubernetes#201]
**Describe the problem**

When I delete the cluster, found that pod `sample-mysql-1` has infinite loop , check the xenon container, it run as follow：
![image](https://user-images.githubusercontent.com/7586502/130932264-e2ec7197-e635-4f06-8177-63d448c09461.png)
But the pod `sample-mysql-2` has been deleted!

**To Reproduce**
cannot reproduce every time, The reason is, `buildPostStart` generator `post-start.sh` , Pod add node to xenon is infinite loop 

1.

**Expected behavior**

**Environment:**

- RadonDB MySQL version:

**Comment by andyli029** [comment]
Long Run.
