### ISSUE TITLE
[bug] git action cant visit .cn

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#208]
**Is your feature request related to a problem? Please describe.**

git action cant visit .cn.

https://github.com/radondb/radondb-mysql-kubernetes/blob/main/Dockerfile#L26

**Describe the solution you'd like**

change to `FROM gcr.io/distroless/static:nonroot`

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
related to #118,
see change log: 
https://github.com/radondb/radondb-mysql-kubernetes/commit/795433d2250ec4d3dc3d7a6075df850d0a7faa78

any other solutions?

**Comment by runkecheng** [comment]
.cn镜像更改为.io

> related to #118,
> see changes in this pr:
> [795433d](https://github.com/radondb/radondb-mysql-kubernetes/commit/795433d2250ec4d3dc3d7a6075df850d0a7faa78)
> 
> any other solutions?

You cannot use `.io` in China, and `.cn` cannot be used for git action. Is there any other purpose for this link to use .io?

**Comment by hustjieke** [comment]
> > related to #118,
> > see changes in this pr:
> > [795433d](https://github.com/radondb/radondb-mysql-kubernetes/commit/795433d2250ec4d3dc3d7a6075df850d0a7faa78)
> > any other solutions?
> 
> You cannot use `.io` in China, and `.cn` cannot be used for git action. Is there any other purpose for this link to use .io?
> 
> I have tested that the image using `.io` can also run normally

https://kubesphere.com.cn/forum/d/1084-gcr-azk8s-cn
Maybe we can learn from Kubershpere when download image in Chinal

**Comment by runkecheng** [comment]
> > > related to #118,
> > > see changes in this pr:
> > > [795433d](https://github.com/radondb/radondb-mysql-kubernetes/commit/795433d2250ec4d3dc3d7a6075df850d0a7faa78)
> > > any other solutions?
> > 
> > 
> > You cannot use `.io` in China, and `.cn` cannot be used for git action. Is there any other purpose for this link to use .io?
> > I have tested that the image using `.io` can also run normally
> 
> https://kubesphere.com.cn/forum/d/1084-gcr-azk8s-cn
> Maybe we can learn from Kubershpere when download image in Chinal

good idea!
