### ISSUE TITLE
[feature] Delete backup container and job redundant parameters.

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#225]
**Is your feature request related to a problem? Please describe.**

Some parameters have been filled in by the controller, no need to fill in environment variables

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andyli029** [comment]
Link #221

**Comment by andyli029** [comment]
Fixed by  https://github.com/radondb/radondb-mysql-kubernetes/pull/197
