### ISSUE TITLE
Eight S3 backup jobs are created, but 11 backup files are generated

### ISSUE THREAD

**Issue by qianfen2021** [radondb/radondb-mysql-kubernetes#237]
**Describe the problem**

1、create eight S3 backup jobs
![image](https://user-images.githubusercontent.com/86407305/134791518-f4ca0e08-9c45-472f-91a6-796ff1556d84.png)
2、11 backup files are generated
![image](https://user-images.githubusercontent.com/86407305/134791553-cfcbff28-0024-4bec-871e-10473bf2cf21.png)

**To Reproduce**
1、copy mysql_v1alpha1_backup.yaml file to create 8 backup jobs，the file path：
https://github.com/radondb/radondb-mysql-kubernetes/blob/main/config/samples/mysql_v1alpha1_backup.yaml

2、rename bakup yaml  file metadata.name，each file has a different metadata.name

3、kubectl apply -f mysql_v1alpha1_backup.yaml

**Expected behavior**

8 backup files are generated

**Environment:**

- RadonDB MySQL version:

**Comment by acekingke** [comment]
When you Add `historyLimit: 10` in the backup yaml file, It do not happened

**Comment by acekingke** [comment]
![image](https://user-images.githubusercontent.com/7586502/134841308-927e1a8a-e86f-4038-ba46-f614d857c585.png)
When backup job Created， they need next reconcile to `updateStatus`, but When the backup job create, May be after `SyncFn` the Job is completed， but this time backup Status not change， when  next reconcile it will create job again, Cause this problem.

**Comment by andyli029** [comment]
When it is first created, this s.job.ObectMeta.CreateTimestamp is 0, and the status of the backup will not be updated.
