### ISSUE TITLE
[feature]Create a user through CRD，grant all and insert permissions，take all permissions

### ISSUE THREAD

**Issue by qianfen2021** [radondb/radondb-mysql-kubernetes#248]
**Is your feature request related to a problem? Please describe.**
1、create a user through CRD，the yaml setting like this:
![image](https://user-images.githubusercontent.com/86407305/135221804-70b82dd4-e8ab-4b77-9fb4-c5bea25b9fde.png)
2、mysql not support grant all and insert permissions，so report syntax error

**Describe the solution you'd like**

grant all and insert permissions，take all permissions

**Describe alternatives you've considered**

**Additional context**

**Comment by runkecheng** [comment]
![3f23e87e77c4a14c0d3443f0864c001](https://user-images.githubusercontent.com/68526782/135222652-775923c0-d18e-483b-afc7-63fd9af4a217.png)
`All` cannot be parallel with other permissions in mysql. I will optimize this problem in subsequent versions through:
- Restrict `ALL` and other permissions from appearing at the same time
- Select `ALL` directly
