### ISSUE TITLE
[bug] The update in the cluster directory did not trigger an action.

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#255]
**Is your feature request related to a problem? Please describe.**

- The update in the cluster directory did not trigger an action.
- `mysqluser`-related folders also need to be able to trigger actions

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andyli029** [comment]
https://github.com/radondb/radondb-mysql-kubernetes/pull/277
