### ISSUE TITLE
[bug]while writing data to cluster,add nodes from 3 to 5，the new node is not added to the cluster

### ISSUE THREAD

**Issue by qianfen2021** [radondb/radondb-mysql-kubernetes#309]
**Describe the problem**
1.use sysbench tools writing data to cluster，add nodes from 3 to 5
2.the new node is not added to the cluster
<img width="813" alt="d43a87539dcf9b5d7388e8395f6d55e" src="https://user-images.githubusercontent.com/86407305/143370325-ccfadc2f-2743-42ba-849a-459951cecf50.png">

**To Reproduce**

1.use sysbench tools writing data to cluster
2.modify mysql_v1alpha1_mysqlcluster.yaml file spec.replicas from 3 to 5
3.kubectl apply -f  mysql_v1alpha1_mysqlcluster.yaml 

**Expected behavior**

the new node is  added to the cluster

**Environment:**

- RadonDB MySQL version:

**Comment by acekingke** [comment]
fix it in  https://github.com/acekingke/xenon/tree/LogPosInConfig
