### ISSUE TITLE
3 pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by wuruipeng404** [radondb/radondb-mysql-kubernetes#313]
**Describe the problem**

![image](https://user-images.githubusercontent.com/34570968/143412710-0b06fb99-cdbc-474a-a687-2630c0f827ca.png)

**To Reproduce**

**Expected behavior**

**Environment:**
- Kubernetes version: v1.22.3
- Helm version: v3.7.1

- RadonDB MySQL version: default

**Comment by runkecheng** [comment]
What type of storage is used?

**Comment by andyli029** [comment]
@2019zgs

**Comment by GuishengZhou** [comment]
maybe  disk  freeed
