### ISSUE TITLE
How to get the backup I want from S3？

### ISSUE THREAD

**Issue by fisher-1** [radondb/radondb-mysql-kubernetes#372]
According to the test, my s3 backup file is in the format of "backup_202211810457", when I have multiple mysql clusters, how do I distinguish which backup is what I need?

**Comment by runkecheng** [comment]
Hello, you can use different bucket to save backup data for different clusters.

**Comment by fisher-1** [comment]
Thank you for your reply, if I have multiple clusters, I have to add new buckets every time I create a cluster, too many buckets are not easy to manage. 
I want several clusters to be backed up to the same bucket, is there any other way to distinguish which cluster the backup belongs to?

**Comment by acekingke** [comment]
This is a good question, but we think that if one more clusters with only one bucket to backup, when a bucket is deleted, all clusters backups will be lost.

**Comment by fisher-1** [comment]
> This is a good question, but we think that if one more clusters with only one bucket to backup, when a bucket is deleted, all clusters backups will be lost.

We don't usually change the configuration of S3. Now the situation is that our backups on S3 are distinguished by bucket names, such as "mysqlbak-***", "mongobak-***", under the same bucket, backups are distinguished by cluster names, such as "cluster-test", "cluster-product", "cluster-pre" and so on.

**Comment by runkecheng** [comment]
I think the feature of `custom backup prefix` can be added.  @andyli029

**Comment by andyli029** [comment]
> I think the feature of `custom backup prefix` can be added. @andyli029

ACK.
