### ISSUE TITLE
[question] Whether scheduled backups are supported？

### ISSUE THREAD

**Issue by fisher-1** [radondb/radondb-mysql-kubernetes#374]
Can I add a scheduled task to back up when the cluster is created or the configuration is changed?

**Comment by runkecheng** [comment]
Do you mean a timed backup? its currently under development. If you have any suggestions you can add below this Issue. https://github.com/radondb/radondb-mysql-kubernetes/issues/215

**Comment by fisher-1** [comment]
> Do you mean a timed backup? its currently under development. If you have any suggestions you can add below this Issue. #215
yes. We look forward to the launch of this feature！

**Comment by acekingke** [comment]
WIP， Just Waiting...
