### ISSUE TITLE
[feature] Support the more elegant way to rebuild node.

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#385]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- Add a label to the node that needs to be rebuilt, then operator reconstruct the node according to the label.

- Automatically rebuild nodes for certain specific circumstances

**Describe alternatives you've considered**

**Additional context**

**Comment by acekingke** [comment]
1. Use lable the pod
2. use Cr
