### ISSUE TITLE
[bug] Physical crash may cause Xenon to start failed.

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#403]
**Describe the problem**

Xenon recovers PANIC in the startup process, if Xenon starts failure, it will not be restarted automatically, and it is in an unhealthy state.

**To Reproduce**

Restart the K8S physical node, this situation occurs about one-fifth probability.

**Expected behavior**

we should check this situation automatically and restart Xenon.

**Environment:**

- RadonDB MySQL version:

**Comment by qianfen2021** [comment]
radondb/mysql-sidecar:latest   test ok
