### ISSUE TITLE
[sidecar] Use unbuffered channel, it is possible to lose the signal.

### ISSUE THREAD

**Issue by mgw2168** [radondb/radondb-mysql-kubernetes#412]
**Describe the problem**

If you use unbuffered channel, it is possible to lose the signal.

**To Reproduce**

If Ctrl + C or Kill occurs when it is blocked before <- stop, the program will stop.

**Expected behavior**

Ctrl+C or Kill when blocking befor <-stop , the program will also stop.

**Environment:**

- RadonDB MySQL version:
v2.1.2

**reference**
https://blog.wu-boy.com/2021/03/why-use-buffered-channel-in-signal-notify/

**Comment by andyli029** [comment]
@mgw2168 
Add link.

**Comment by mgw2168** [comment]
fix in: https://github.com/radondb/radondb-mysql-kubernetes/pull/411
