### ISSUE TITLE
unknown field "podPolicy" in com.radondb.mysql.v1alpha1.MysqlCluster.spec

### ISSUE THREAD

**Issue by club326** [radondb/radondb-mysql-kubernetes#420]
when I try to install mysql-operator v2.1.2 in kubernet 1.18.9, execute command like this
`kubectl apply -f https://github.com/radondb/radondb-mysql-kubernetes/releases/latest/download/mysql_v1alpha1_mysqlcluster.yaml`

However, there are some unexpected errors happed, the error like this，

`error: error validating "radondb_mysqlcluster.yaml": error validating data: ValidationError(MysqlCluster.spec): unknown field "podPolicy" in com.radondb.mysql.v1alpha1.MysqlCluster.spec; if you choose to ignore these errors, turn validation off with --validate=false`

evenif I add `--validate=false`,there are still some errors

`create Pod sample-mysql-0 in StatefulSet sample-mysql failed error: Pod "sample-mysql-0" is invalid: [spec.containers[2].image: Required value, spec.initContainers[0].image: Required value]`

**Is the template file missing some necessary parameters？**

**Comment by runkecheng** [comment]
Hello, this may be that the CRD version is inconsistent with the Operator version.
You can [delete the old CRD](https://github.com/radondb/radondb-mysql-kubernetes/blob/main/docs/zh-cn/deploy_radondb-mysql_operator_on_k8s.md#%E5%8D%B8%E8%BD%BD%E8%87%AA%E5%AE%9A%E4%B9%89%E8%B5%84%E6%BA%90) and [reinstall the Operator](https://github.com/radondb/radondb-mysql-kubernetes/blob/main/docs/zh-cn/deploy_radondb-mysql_operator_on_k8s.md#%E9%83%A8%E7%BD%B2%E6%AD%A5%E9%AA%A4).

**Comment by runkecheng** [comment]
Helm cannot update CRD automatically, so when CRD changes, you must manually remove the old CRD to avoid conflicts.

**Comment by club326** [comment]
thanks for reply. delete CRD is ok for this issue
