### ISSUE TITLE
Too expensive to update s3 datasource

### ISSUE THREAD

**Issue by Nrehearsal** [radondb/radondb-mysql-kubernetes#425]
Information of s3 was injected in pods with environment variables, so when I edit the s3 secret directly, related environment variables in pods would not be updated.
if I update ```backupSecretName``` to a new value, this action will trigger pod rebuild. 
Is it possible to move s3 info to backup CRD, and inject it to job's env?

**Comment by andyli029** [comment]
@acekingke

**Comment by acekingke** [comment]
Move it to backup， May Cause restore cluster problem.
