### ISSUE TITLE
按照文档安装，sample-mysql-0一直无限重启

### ISSUE THREAD

**Issue by wss434631143** [radondb/radondb-mysql-kubernetes#440]
按照官方文档：https://github.com/radondb/radondb-mysql-kubernetes/blob/main/docs/zh-cn/deploy_radondb-mysql_operator_on_k8s.md 来部署

部署命令：
helm repo add radondb https://radondb.github.io/radondb-mysql-kubernetes/
helm install demo radondb/mysql-operator
kubectl apply -f https://github.com/radondb/radondb-mysql-kubernetes/releases/latest/download/mysql_v1alpha1_mysqlcluster.yaml

环境：
azure aks v1.21.2 三个node节点

现象：
sample-mysql-0一直无限重启

报错：
(combined from similar events): Readiness probe failed: [31mxenon.go:49: unexpected error: get.client.error[dial tcp 10.139.4.8:8801: connect: connection refused][39m 2022/04/11 02:58:45.733344 common.go:35: [PANIC] get.client.error[dial tcp 10.139.4.8:8801: connect: connection refused] panic: [PANIC] get.client.error[dial tcp 10.139.4.8:8801: connect: connection refused] goroutine 1 [running]: xbase/xlog.(*Log).Panic(0xc0001862c0, 0x7f5246, 0x2, 0xc0000f5d08, 0x1, 0x1) /go/src/github.com/radondb/xenon/src/xbase/xlog/xlog.go:164 +0x157 cli/cmd.ErrorOK(0x86b6c0, 0xc0001869a0) /go/src/github.com/radondb/xenon/src/cli/cmd/common.go:35 +0x245 cli/cmd.xenonPingCommandFn(0xc0001d8480, 0xa907a0, 0x0, 0x0) /go/src/github.com/radondb/xenon/src/cli/cmd/xenon.go:49 +0x94 vendor/github.com/spf13/cobra.(*Command).execute(0xc0001d8480, 0xa907a0, 0x0, 0x0, 0xc0001d8480, 0xa907a0) /go/src/github.com/radondb/xenon/src/vendor/github.com/spf13/cobra/command.go:603 +0x24b vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa59480, 0xc000000180, 0xc0000f5f78, 0x407ce5) /go/src/github.com/radondb/xenon/src/vendor/github.com/spf13/cobra/command.go:689 +0x2d0 vendor/github.com/spf13/cobra.(*Command).Execute(...) /go/src/github.com/radondb/xenon/src/vendor/github.com/spf13/cobra/command.go:648 main.main() /go/src/github.com/radondb/xenon/src/cli/cli.go:43 +0x31

<img width="948" alt="WechatIMG6325" src="https://user-images.githubusercontent.com/6138576/162659451-b7eb7fed-9cf2-42bb-b8b5-3c0e376de841.png">
<img width="723" alt="WechatIMG6328" src="https://user-images.githubusercontent.com/6138576/162659464-e5b40574-da0d-42b5-97de-f70ba22a6156.png">

![33333333](https://user-images.githubusercontent.com/6138576/162660061-8df20490-c3d0-42e5-8f3e-38cbbdf84fce.jpg)

![4444444](https://user-images.githubusercontent.com/6138576/162660167-ee9e6126-36ea-476a-b816-5dfa67feaf60.jpg)

**Comment by andyli029** [comment]
1.  Add host about`:: 1` host  for  `root` in the MySQL to 
https://github.com/radondb/radondb-mysql-kubernetes/pull/187
