### ISSUE TITLE
[feature] Support ipv6 address.

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#441]
**Is your feature request related to a problem? Please describe.**

`127.0.0.1` in ipv6 is `::1`, Xenon May use `:: 1` to connect mysql instead of `127.0.0.1`, so we also need to provide the default account of `::1`.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by acekingke** [comment]
It Maybe donot set localhost in /etc/hosts

**Comment by runkecheng** [comment]
https://stackoverflow.com/questions/30139358/changing-etc-hosts-with-sed-command
