### ISSUE TITLE
[bug]restore new cluster from s3 object storage in mysql 8.0，mysql container can't start

### ISSUE THREAD

**Issue by qianfen2021** [radondb/radondb-mysql-kubernetes#448]
**Describe the problem**
restore new cluster from s3 object storage in mysql 8.0，mysql container can't start
<img width="930" alt="e92aa036cf0ed53f8d5c443f14028c7" src="https://user-images.githubusercontent.com/86407305/163104876-0ec486ba-af39-4b1b-85c2-8982c77986ff.png">

**To Reproduce**

1.Backup from cluster，then produce s3 back file
2.restore new cluster from s3 object storage

**Expected behavior**
new cluster start successful

**Environment:**
mysql version 8.0

- RadonDB MySQL version:

**Comment by runkecheng** [comment]
<img width="1216" alt="05c27931f4b73ef781b40c2cea6e4d3" src="https://user-images.githubusercontent.com/68526782/163152099-59f9521a-4751-466e-bb68-4ac9097c3d2b.png">
