### ISSUE TITLE
mysql8.0问题，设置mysqlVersion: "8.0"  init-sidecar 依然初始化失败，提醒：invalid mysql version, currently we only support 5.7 or 8.0

### ISSUE THREAD

**Issue by myitsite** [radondb/radondb-mysql-kubernetes#458]
容器日志

 panic: invalid mysql version, currently we only support 5.7 or 8.0

 

 goroutine 1 [running]:

 github.com/radondb/radondb-mysql-kubernetes/sidecar.NewInitConfig(0xaad95b)

 	/workspace/sidecar/config.go:135 +0x1065

 main.main()

 	/workspace/cmd/sidecar/main.go:91 +0x116

**Comment by runkecheng** [comment]
你好，我们将在v2.2.0版本支持mysql8，目前按照文档安装的是v2.1.4版本。

**Comment by myitsite** [comment]
好的，谢谢作者，支持

**Comment by runkecheng** [comment]
你好，我们刚刚发布了[v2.2.0-alpha.1](https://github.com/radondb/radondb-mysql-kubernetes/releases/tag/v2.2.0-alpha.1)，你可以使用这个版本来部署，体验MySQL8。
