### ISSUE TITLE
[feature] Add check for shadowed variables.

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#467]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

```
go tool vet -shadow=true ./
```

ref: https://github.com/barakmich/go-nyet

Add check in ci.

**Describe alternatives you've considered**

**Additional context**

**Comment by runkecheng** [comment]
`go nyet` may be misjudgment, so it can only be used as a self -examination and cannot be used as a standard.

**Comment by acekingke** [comment]
```
go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
go vet -vettool=$(which shadow)
```
