### ISSUE TITLE
[feature] forbidden `lower_case_table_names` modify in my.cnf

### ISSUE THREAD

**Issue by acekingke** [radondb/radondb-mysql-kubernetes#477]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhl003** [comment]
In  MySQL 8.0 `lower_case_table_names` allow define in CRD  before MySQL cluster creating and  disallow modify when cluster is already running 
But in MySQL 5.7 and lower  `lower_case_table_names` should allow modify any time

@acekingke
