### ISSUE TITLE
[bug]in crd file clusterName field like this,in the backup cr file is clustername

### ISSUE THREAD

**Issue by qianfen2021** [radondb/radondb-mysql-kubernetes#499]
**Describe the problem**

in crd file clusterName field like this,in the backup cr file is clustername
<img width="960" alt="84bb9d8df6cf9f8ad9d140fb73ba4c4" src="https://user-images.githubusercontent.com/86407305/170641718-7bcbc39e-eb12-45c6-94eb-8b02f146df2c.png">

**To Reproduce**

1.deploy mysql operator and mysql cluster
2.kubectl apply -f mysql_v1alpha1_backup.yaml

**Expected behavior**

**Environment:**

- RadonDB MySQL version:
v2.2.0-beta

**Comment by xiao-jay** [comment]
hi @qianfen2021 ,I find the reason,In mysql_v1alpha1_backup.yaml ,the image is radondb/mysql57-sidecar:v2.2.0,but in v2.2.0,the BackupSpec struct is 
```
type BackupSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// To specify the image that will be used for sidecar container.
	// +optional
	// +kubebuilder:default:="radondb/mysql57-sidecar:v2.2.0"
	Image string `json:"image"`

	// HostName represents the host for which to take backup
	HostName string `json:"hostname"`

	// ClusterName represents the cluster name to backup
	ClusterName string `json:"clustname"`

	// History Limit of job
	// +optional
	// +kubebuilder:default:=3
	HistoryLimit *int32 `json:"historyLimit,omitempty"`
}
```
The Solution is  make a new radondb-mysql-kubernetes image self and substitute radondb/mysql57-sidecar:v2.2.0.
Or release a new image version . @andyli029  Can you release a new docker image?

**Comment by xiao-jay** [comment]
> > hi @qianfen2021 ,I find the reason,In mysql_v1alpha1_backup.yaml ,the image is radondb/mysql57-sidecar:v2.2.0,but in v2.2.0,the BackupSpec struct is
> > ```
> > type BackupSpec struct {
> > 	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
> > 	// Important: Run "make" to regenerate code after modifying this file
> > 
> > 	// To specify the image that will be used for sidecar container.
> > 	// +optional
> > 	// +kubebuilder:default:="radondb/mysql57-sidecar:v2.2.0"
> > 	Image string `json:"image"`
> > 
> > 	// HostName represents the host for which to take backup
> > 	HostName string `json:"hostname"`
> > 
> > 	// ClusterName represents the cluster name to backup
> > 	ClusterName string `json:"clustname"`
> > 
> > 	// History Limit of job
> > 	// +optional
> > 	// +kubebuilder:default:=3
> > 	HistoryLimit *int32 `json:"historyLimit,omitempty"`
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The Solution is make a new radondb-mysql-kubernetes image self and substitute radondb/mysql57-sidecar:v2.2.0. Or release a new image version . @andyli029 Can you release a new docker image?
> 
> There were some wrong spellings which have been repaired. We will publish a new version soon. #500

pretty good :thumbsup:
