### ISSUE TITLE
How to definition mysql plugin config

### ISSUE THREAD

**Issue by harryand666** [radondb/radondb-mysql-kubernetes#544]
## General Question

Background: We deployed radondb/mysql-operator in K8S, and then used yaml to define Mysql cluster
Discovery: Try to find that this configuration will be loaded into my.cnf through the definition of mysqlOpts.mysqlConf, and will cause a startup error, because the plugin is not loaded during the initial startup process, and the plugin-related configuration cannot be recognized
Question: How to define the configuration of mysql-plugin in yaml (eg audit_log_format: "JSON")

**Comment by runkecheng** [comment]
Already merge, just wait for the next version to be published or use image tag `v2.2.0-beta.2` to test. https://github.com/radondb/radondb-mysql-kubernetes/pull/526

**Comment by harryand666** [comment]
@runkecheng Thanks for the reply, does this pulish work for both mysql 5.7 and mysql 8.0?

**Comment by runkecheng** [comment]
> @runkecheng Thanks for the reply, does this pulish work for both mysql 5.7 and mysql 8.0?

All support
