### ISSUE TITLE
[bug]The cluster is deleted, but the automatic backup job is not deleted

### ISSUE THREAD

**Issue by qianfen2021** [radondb/radondb-mysql-kubernetes#570]
**Describe the problem**

The cluster is deleted, but the automatic backup job is not deleted
![image](https://user-images.githubusercontent.com/86407305/177072173-ac637f7e-bad5-4575-bfc5-5266bd98e346.png)
![image](https://user-images.githubusercontent.com/86407305/177072202-3600c298-eb3f-4297-af2d-a6f59ec0d56d.png)

**To Reproduce**

1.Create a cluster and create a scheduled backup
2.Delete the cluster

**Expected behavior**

**Environment:**
the automatic backup job is deleted

- RadonDB MySQL version:

**Comment by acekingke** [comment]
delete cluster to delete the backup cr , it will use finalizer, do it next version.
