### ISSUE TITLE
the doc create user guid  failed 

### ISSUE THREAD

**Issue by zhuyaguang** [radondb/radondb-mysql-kubernetes#602]
`kubectl apply -f https://raw.githubusercontent.com/radondb/radondb-mysql-kubernetes/main/config/samples/mysql_v1alpha1_mysqluser.yaml `

create user failed 

`error: error validating "https://raw.githubusercontent.com/radondb/radondb-mysql-kubernetes/main/config/samples/mysql_v1alpha1_mysqluser.yaml": error validating data: [ValidationError(MysqlUser.spec): unknown field "tlsOptions" in com.radondb.mysql.v1alpha1.MysqlUser.spec, ValidationError(MysqlUser.spec): unknown field "withGrantOption" in com.radondb.mysql.v1alpha1.MysqlUser.spec]; if you choose to ignore these errors, turn validation off with --validate=false`

doc url : https://github.com/radondb/radondb-mysql-kubernetes/blob/main/docs/zh-cn/mgt_mysqluser.md#MysqlUser

**Comment by runkecheng** [comment]
Hello, we updated the API of the main branch, you can try to pull the code of v2.2.0 and apply this file `config/samples/mysql_v1alpha1_mysqluser.yaml`
