### ISSUE TITLE
How to definition imagePrefix for percona-server

### ISSUE THREAD

**Issue by harryand666** [radondb/radondb-mysql-kubernetes#609]
## General Question

Background: We deployed radondb/mysql-operator in K8S, and then used yaml to define Mysql cluster
Discovery: Operator use default image for percona-server when setup mysql
Question: How to definition imagePrefix for percona-server(we use private container registry)

**Comment by runkecheng** [comment]
https://github.com/radondb/radondb-mysql-kubernetes/blob/main/charts/mysql-operator/values.yaml#L15

**Comment by harryand666** [comment]
Thanks for the reply
