### ISSUE TITLE
after install radondb by helm,create a user and password ,but can not login

### ISSUE THREAD

**Issue by zhuyaguang** [radondb/radondb-mysql-kubernetes#625]
can not login 

![image](https://user-images.githubusercontent.com/8857976/181442875-fd4b579c-0764-45ec-99af-1e53ad7ce59c.png)

create a user : sample_user

password: RadonDB@123

![image](https://user-images.githubusercontent.com/8857976/181442975-423424ee-49b2-4562-a331-844f61f4e0ea.png)

**Comment by runkecheng** [comment]
Check whether your Secret is correct
```
echo -n "RadonDB@123" | base64   
UmFkb25EQkAxMjM=
```

**Comment by zhuyaguang** [comment]
@runkecheng  why RadonDB@123 base64 is different
![image](https://user-images.githubusercontent.com/8857976/181451068-9e365c3a-f798-4d95-9b49-a64f83f21cc2.png)
