### ISSUE TITLE
从NFS备份目录恢复时，nfsServerAddress 的值设置为 nfs服务域名报错

### ISSUE THREAD

**Issue by mainlaodao** [radondb/radondb-mysql-kubernetes#627]
环境：
k3s v1.23.8 
radondb-mysql-kubenetes v2.2.0 
mysql 8
nfs 服务镜像：coolersport/volume-nfs:0.8
主要配置：
spec:
  replicas: 3
  mysqlVersion: "8.0"
  restoreFrom: "hxzj-mysql_202272718119"
  nfsServerAddress: "radondb-nfs-server.default"
  backupSchedule: "0 0/10 * * * *" 

其他大部分是默认值，radondb-nfs-server.default 为nfs SVC 的域名

错误如下：
查看命令：kubectl describe pod/hxzj-mysql-mysql-0 -n hxzj

Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    63s                default-scheduler  Successfully assigned hxzj/hxzj-mysql-mysql-0 to daoge
  Warning  FailedMount  32s (x7 over 63s)  kubelet            MountVolume.SetUp failed for volume "backup" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs radondb-nfs-server.default:/ /var/lib/kubelet/pods/9b57639b-4547-4516-beb4-02d1d53259e7/volumes/kubernetes.io~nfs/backup
Output: mount.nfs: Failed to resolve server radondb-nfs-server.default: Name or service not known

如果nfsServerAddress 改为具体的nfs服务内部IP，可以成功。

多谢各位！

**Comment by runkecheng** [comment]
你好，nfsserveraddress 应该填写 ip 地址，见api描述 https://github.com/radondb/radondb-mysql-kubernetes/blob/main/api/v1alpha1/mysqlcluster_types.go#L87
后续我们会支持自动转换域名。

**Comment by runkecheng** [comment]
域名看起来不完整，可能是由于域名全称超过了最大的字符个数（63），你可以尝试缩短ns名称或者集群名称。

**Comment by mainlaodao** [comment]
@runkecheng 域名没有超过63，可以ping 通。如果不支持域名的话，nfs作为内部服务，ip经常变的，导致使用不方便。谢谢

**Comment by runkecheng** [comment]
> @runkecheng 域名没有超过63，可以ping 通。如果不支持域名的话，nfs作为内部服务，ip经常变的，导致使用不方便。谢谢

nfsserver服务的clusterip一般情况下不会变动，当然，支持域名是更好的办法。
