### ISSUE TITLE
mysql 8.0

### ISSUE THREAD

**Issue by Heyz6** [radondb/radondb-mysql-kubernetes#629]
kubectl apply -f https://github.com/radondb/radondb-mysql-kubernetes/releases/download/v2.2.0/mysql_v1alpha1_mysqlcluster_mysql8.yaml

bash-4.4$ mysql -uradondb_usr -pRadonDB@123
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 79
Server version: 8.0.25-15 Percona Server (GPL), Release 15, Revision a558ec2

Copyright (c) 2009-2021 Percona LLC and/or its affiliates
Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show character set like 'utf8%';
+---------+---------------+--------------------+--------+
| Charset | Description   | Default collation  | Maxlen |
+---------+---------------+--------------------+--------+
| utf8    | UTF-8 Unicode | utf8_general_ci    |      3 |
| utf8mb4 | UTF-8 Unicode | utf8mb4_0900_ai_ci |      4 |
+---------+---------------+--------------------+--------+
2 rows in set (0.00 sec)

if  I want Default sorted character set 
| utf8mb4 | UTF-8 Unicode | utf8mb4_general_ci |      4 |

how to do

**Comment by runkecheng** [comment]
Fill in the parameters you need at:
https://github.com/radondb/radondb-mysql-kubernetes/blob/main/config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml#L27
