### ISSUE TITLE
How to customize the mysql version

### ISSUE THREAD

**Issue by Heyz6** [radondb/radondb-mysql-kubernetes#637]
https://github.com/radondb/radondb-mysql-kubernetes/releases/download/v2.2.0/mysql_v1alpha1_mysqlcluster_mysql8.yaml
apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlCluster
metadata:
  name: sample
spec:
  replicas: 2
  mysqlVersion: "8.0"

May I ask how I can customize the mysql version? Is there any other way to compile it? It's an urgent need
I need mysql version 8.0.29

**Comment by zhl003** [comment]
We don't support custom mysql version yet，but it will be support soon

**Comment by Heyz6** [comment]
Is there an estimated support time？ @zhl003

**Comment by KID-G** [comment]
> Is there an estimated support time？ @zhl003

The specific time is not yet available, but it is not far away. Thank you for your attention.
