### ISSUE TITLE
将mysql8.0的版本降低到5.7的版本之后，状态一直为Initializing

### ISSUE THREAD

**Issue by anan1310** [radondb/radondb-mysql-kubernetes#638]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/75241895/183335703-873f4d87-ef47-41cf-af48-91132cbd1086.png">

**Comment by runkecheng** [comment]
你好，目前不支持直接从8.0直接降级到5.7。

**Comment by anan1310** [comment]
> 你好，目前不支持直接从8.0直接降级到5.7。

那我想问一下 那删除了8.0的版本 然后重新部署也是这样的 有没有什么解决办法

**Comment by runkecheng** [comment]
> > 你好，目前不支持直接从8.0直接降级到5.7。
> 
> 那我想问一下 那删除了8.0的版本 然后重新部署也是这样的 有没有什么解决办法

请问你是怎么删除的，卸载集群要通过删除 mysqlcluster cr来卸载，否则不会删除pvc；如果pv使用mysql8初始化过，再绑定到mysql57就可能会无法启动。

**Comment by KID-G** [comment]
> > 你好，目前不支持直接从8.0直接降级到5.7。
> 
> 那我想问一下 那删除了8.0的版本 然后重新部署也是这样的 有没有什么解决办法

可以参考公众号“**RadonDB 开源社区**”最新一期文章关于卸载时的注意事项部分。

**Comment by anan1310** [comment]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/75241895/183355874-a009e8dd-6bae-4889-9a24-c3384c51ec05.png">
我先通过这样的方式删除，删除了mysqlcluster 然后在部署5.7版本的 我觉着这样的步骤完全是可行的 至于PVC我使用的storreClass ,如果PVC删除了之后 对应的pv也会自动删除
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/75241895/183356370-a8efda26-5eac-436a-ac31-f04e56751389.png">

**Comment by runkecheng** [comment]
> <img alt="image" width="693" src="https://user-images.githubusercontent.com/75241895/183355874-a009e8dd-6bae-4889-9a24-c3384c51ec05.png">
> 
> 我先通过这样的方式删除，删除了mysqlcluster 然后在部署5.7版本的 我觉着这样的步骤完全是可行的 至于PVC我使用的storeClass ,如果PVC删除了之后 对应的pv也会自动删除
> <img alt="image" width="1050" src="https://user-images.githubusercontent.com/75241895/183356370-a8efda26-5eac-436a-ac31-f04e56751389.png">

这个步骤是对的，可以看看init-sidecar和init-mysql是否有报错。

**Comment by anan1310** [comment]
> 

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/75241895/183358278-38330034-7429-4891-b3d0-fa5d4f8bbbb0.png">
我这里已经PVC和pv已经进行了绑定
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/75241895/183358377-60d22746-24f7-4a37-99e3-a5e8f7b1735b.png">
错误信息提示
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/75241895/183358651-057eefcd-afe3-40d3-a59d-1c7b8ccbe857.png">

**Comment by runkecheng** [comment]
> > 
> 
> <img alt="image" width="1218" src="https://user-images.githubusercontent.com/75241895/183358278-38330034-7429-4891-b3d0-fa5d4f8bbbb0.png">
> 
> 我这里已经PVC和pv已经进行了绑定
> <img alt="image" width="1057" src="https://user-images.githubusercontent.com/75241895/183358377-60d22746-24f7-4a37-99e3-a5e8f7b1735b.png">
> 
> 错误信息提示
> <img alt="image" width="1199" src="https://user-images.githubusercontent.com/75241895/183358651-057eefcd-afe3-40d3-a59d-1c7b8ccbe857.png">

看截图显示已经调度成功了，pod启动时短暂出现调度失败是正常的。

**Comment by anan1310** [comment]
> > > 
> > 
> > 
> > <img alt="image" width="1218" src="https://user-images.githubusercontent.com/75241895/183358278-38330034-7429-4891-b3d0-fa5d4f8bbbb0.png">
> > 我这里已经PVC和pv已经进行了绑定
> > <img alt="image" width="1057" src="https://user-images.githubusercontent.com/75241895/183358377-60d22746-24f7-4a37-99e3-a5e8f7b1735b.png">
> > 错误信息提示
> > <img alt="image" width="1199" src="https://user-images.githubusercontent.com/75241895/183358651-057eefcd-afe3-40d3-a59d-1c7b8ccbe857.png">
> 
> 看截图显示已经调度成功了，pod启动时短暂出现调度失败是正常的。
然后进行了日志的查看 
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/75241895/183360012-47d13e4d-e946-465c-bd1f-7c88a6129e8c.png">
等待了很长时间都是这样的
<img width="751" alt="image" src="https://user-images.githubusercontent.com/75241895/183360220-130adb6f-695d-4f52-bcad-a2c407798f84.png">

**Comment by runkecheng** [comment]
你需要指定容器:
```
kubectl logs sample-mysql-0 -c init-sidecar
kubectl logs sample-mysql-0 -c init-mysql
```

**Comment by anan1310** [comment]
> 你需要指定容器 @anan1310
> 
> ```
> kubectl logs sample-mysql-0 -c init-sidecar
> kubectl logs sample-mysql-0 -c init-mysql
> ```
可行了 就是等待的时间比较长 等待了大约20分钟之后它初始化成功了 这块是正常的吗

**Comment by runkecheng** [comment]
> 

一般不会这么久，要看具体环境配置。

**Comment by anan1310** [comment]
好的 麻烦您了呀
