### ISSUE TITLE
按照官方的文档使用nfs备份，最后的状态一直为Completed！

### ISSUE THREAD

**Issue by anan1310** [radondb/radondb-mysql-kubernetes#639]
报错详情
<img width="941" alt="image" src="https://user-images.githubusercontent.com/75241895/183403495-71a98c76-506a-453a-918f-9ad9ffdc2d12.png">

1、查看容器内日志错误信息
<img width="810" alt="image" src="https://user-images.githubusercontent.com/75241895/183402754-8bfc3fa8-4e05-4fb4-8c56-7c8f8b7fe95e.png">
2、但是已经提示启动成功了
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/75241895/183402926-50346dc1-ad0e-40f6-99d5-1ddfa89861d2.png">
3、文件如下
<img width="565" alt="image" src="https://user-images.githubusercontent.com/75241895/183403160-db2e1c1b-40ad-46bf-9210-0706de9e0d3a.png">
@runkecheng  您有时间给瞅一眼

**Comment by acekingke** [comment]
这个备份已经失败了，但是backup的pod 并没有捕捉到错误，导致backup显示complate， 现在正在修复。谢谢

**Comment by acekingke** [comment]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/7586502/183551554-854f00f3-969d-4e13-b6aa-9d42dac8540b.png">
关于这个报错，请检查operator 与sidecar 是否是同一个版本，以及 
```
kubectl get roles conn-mysql 
```
查看 是否有 `jobs.batch` 权限，如果没有权限，建议安装正确的版本

**Comment by anan1310** [comment]
@acekingke 
1、operator版本
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/75241895/183559759-7c720ad8-d5c9-46bd-abba-0f0d4cfb8aac.png">
2、mysql版本
<img width="602" alt="image" src="https://user-images.githubusercontent.com/75241895/183559864-cd409427-b701-423d-9359-1ea056abefdd.png">
3、sidecar版本
<img width="580" alt="image" src="https://user-images.githubusercontent.com/75241895/183559976-dd11495b-196d-46e7-bd72-4cc27c1a776d.png">
4、权限存在
<img width="926" alt="image" src="https://user-images.githubusercontent.com/75241895/183560093-c1dd9046-a96b-49d5-a1fa-b8480b4859b8.png">

**Comment by anan1310** [comment]
同样的方式我使用s3的方式备份 同样没有成功 我怀疑是不是版本的问题 但是我找不到对应的版本在哪一块

**Comment by acekingke** [comment]
CRD 是否更换？
