### ISSUE TITLE
部署完集群之后一直是初始化的状态！

### ISSUE THREAD

**Issue by anan1310** [radondb/radondb-mysql-kubernetes#645]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/75241895/183811725-49c394d5-3eaf-43ec-83e4-8b6f7a094486.png">
查看容器组 发现并么有创建容器
<img width="686" alt="image" src="https://user-images.githubusercontent.com/75241895/183812038-6931c14f-f5c7-43bc-a9b7-ebfc99735692.png">
<img width="675" alt="image" src="https://user-images.githubusercontent.com/75241895/183812196-386138d1-2d43-443b-9882-61fcc20f43bb.png">

**Comment by runkecheng** [comment]
可以查看一下operator manager容器的日志

**Comment by anan1310** [comment]
还有一个问题 创建完超级用户 修改密码之后就不能再进行登陆 这个是正常的吗

**Comment by anan1310** [comment]
还有一个问题 创建完超级用户 修改密码之后就不能再进行登陆 这个是正常的吗

**Comment by runkecheng** [comment]
> 还有一个问题 创建完超级用户 修改密码之后就不能再进行登陆 这个是正常的吗

你是怎么创建的呢，目前版本还需要手动创建，管理超级用户，mysqluser crd是不支持with grant的

**Comment by anan1310** [comment]
第一步：先部署serets
<img width="930" alt="image" src="https://user-images.githubusercontent.com/75241895/183833039-69e265aa-b5df-4f62-a206-8f5c0b70c6a6.png">
第二步：部署mysql Users
<img width="541" alt="image" src="https://user-images.githubusercontent.com/75241895/183833225-c9576e34-afc9-4bdf-8774-b253a64e32eb.png">
现在可以进行登陆访问，如果我修改secrets中的密码 重新部署 然后用修改之后的密码进行登陆就不行了

**Comment by runkecheng** [comment]
因为2.2.0还不能这么改密码，我们马上会发2.2.1，就支持这么操作了。

**Comment by anan1310** [comment]
> 因为2.2.0还不能这么改密码，我们马上会发2.2.1，就支持这么操作了。

目前只能就是第一次创建完成之后就不能修改了吧

**Comment by runkecheng** [comment]
> > 因为2.2.0还不能这么改密码，我们马上会发2.2.1，就支持这么操作了。
> 
> 目前只能就是第一次创建完成之后就不能修改了吧

是的，现在可以删除重建用户
