### ISSUE TITLE
使用NFS 备份提示错误

### ISSUE THREAD

**Issue by Heyz6** [radondb/radondb-mysql-kubernetes#648]
https://github.com/radondb/radondb-mysql-kubernetes/blob/main/docs/zh-cn/backup_and_restoration_nfs.md #参照官方文档
helm fetch radondb/mysql-operator
helm install demo radondb/mysql-operator --set nfsBackup.installServer=true  --set nfsBackup.volume.createLocalPV=true
[root@node1 ~]# kubectl get svc radondb-nfs-server --template={{.spec.clusterIP}}
10.233.58.79
----------------------------------------------------------Backup yaml
apiVersion: mysql.radondb.com/v1alpha1
kind: Backup
metadata:
  name: backup-sample
spec:
  image: radondb/mysql57-sidecar:v2.2.0
  hostName: sample-mysql-0
  clusterName: sample
  nfsServerAddress: "10.233.58.79"

[root@node1 ~]# kubectl logs radondb-nfs-server-z75tz 
Serving /exports
Serving /
rpcinfo: can't contact rpcbind: : RPC: Unable to receive; errno = Connection refused
Starting rpcbind
exportfs: / does not support NFS export
NFS started

但是提示 报错

**Comment by acekingke** [comment]
请检查node节点是否安装nfs client
