### ISSUE TITLE
[bug]The automatic nfs backup exceeds the disk capacity. As a result, the original cluster cannot read and write data

### ISSUE THREAD

**Issue by qianfen2021** [radondb/radondb-mysql-kubernetes#663]
**Describe the problem**

The automatic nfs backup exceeds the disk capacity. As a result, the original cluster cannot read and write data

**To Reproduce**

1.Automatic nfs backup once per second,and pvc size is 1G,then exceeds the disk capacity
2.the original cluster cannot read and write data

**Expected behavior**

**Environment:**

- RadonDB MySQL version:
- v2.2.1

**Comment by acekingke** [comment]
I check it，  and I found that the mysql cluster pod just attach nfs server driver during init-sidecar container, So this problem should be the disk of node machine is full.
