### ISSUE TITLE
Automatic Backup By default, the backup is performed from Pod 0.The node where Pod 0 resides fails and cannot be backed up 

### ISSUE THREAD

**Issue by qianfen2021** [radondb/radondb-mysql-kubernetes#669]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Automatic Backup By default, the backup is performed from Pod 0.The node where Pod 0 resides fails and cannot be backed up 。

**Describe alternatives you've considered**

**Additional context**

**Comment by acekingke** [comment]
It is normal way.
