### ISSUE TITLE
从库出现1062 主键冲突

### ISSUE THREAD

**Issue by gitzhuyongfu** [radondb/radondb-mysql-kubernetes#684]
k8s集群上装了randondb，因节点宕机导致主节点漂移到另外的pod，后来排查从节点日志出现了2022-09-01T16:26:03.900147+08:00 5946 [Warning] Slave: Duplicate entry '2080628' for key 'PRIMARY' Error_code: 1062
这个如何处理？

**Comment by runkecheng** [comment]
你可以尝试重建节点。https://github.com/radondb/radondb-mysql-kubernetes/blob/main/docs/zh-cn/rebuild.md

**Comment by gitzhuyongfu** [comment]
无法重建！这个如何解决？
Rebuilding is danagerous job, Before doing this, please make sure your cluster data is safe and consistent.
Do you want to do it (y/n)?y
Pod mysql-radondb-mysql-1 is running.
Pod in Raft is not in invalid state, please check your cluster status.

**Comment by runkecheng** [comment]
> 无法重建！这个如何解决？ Rebuilding is danagerous job, Before doing this, please make sure your cluster data is safe and consistent. Do you want to do it (y/n)?y Pod mysql-radondb-mysql-1 is running. Pod in Raft is not in invalid state, please check your cluster status.

你可以手动指定要重建的节点，参考如下格式：
```
kubectl label pods sample-mysql-0 rebuild=true 
```

**Comment by gitzhuyongfu** [comment]
已打标需重建的pod，然后再手工执行rebuild脚本依然是上述的问题，没有重建成功
Rebuilding is danagerous job, Before doing this, please make sure your cluster data is safe and consistent.
Do you want to do it (y/n)?y
Pod mysql-radondb-mysql-1 is running.
Pod in Raft is not in invalid state, please check your cluster status.

**Comment by runkecheng** [comment]
> 因为设置了标签之后没有效果，没看到pod有重建的动作，所以执行了rebuild.sh，但是好像也是没有效果。我这个是环境是基于master分支的helm版本安装的

麻烦提供一下当前安装的operator版本和MySQL版本：
```
helm list
kubectl get mysqlcluster -oyaml | grep Version
```

**Comment by gitzhuyongfu** [comment]
NAME 	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
mysql	mysql-sit	2       	2022-08-30 12:12:16.719411785 +0800 CST	deployed	radondb-mysql-1.0.0	5.7.34  

chart: radondb-mysql-1.0.0
mysql：5.7.34

**Comment by runkecheng** [comment]
> NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION mysql mysql-sit 2 2022-08-30 12:12:16.719411785 +0800 CST deployed radondb-mysql-1.0.0 5.7.34
> 
> chart: radondb-mysql-1.0.0 mysql：5.7.34

这个是早期的纯chart版本，已经停止维护，你可以按照首页的步骤安装operator版本v2.1.1，https://github.com/radondb/radondb-mysql-kubernetes#steps

**Comment by gitzhuyongfu** [comment]
根据样本安装设置root密码出现错误：
The MysqlCluster "sample" is invalid: spec.mysqlOpts.rootPassword: Unsupported value: "RadonDB@123": supported values: ""

**Comment by zhl003** [comment]
> 根据样本安装设置root密码出现错误： The MysqlCluster "sample" is invalid: spec.mysqlOpts.rootPassword: Unsupported value: "RadonDB@123": supported values: ""

新版本的operator里面rootPassword强制设置成空，root用户不再提供给外部访问，你需要修改下cr把这个字段的值置空
