### ISSUE TITLE
在 Ingress 上，应该选择哪个 service？

### ISSUE THREAD

**Issue by aliuq** [radondb/radondb-mysql-kubernetes#690]
请问下我应该选择 sample-leader 还是 sample-mysql？

![image](https://user-images.githubusercontent.com/11707934/188860958-3911c65f-e3ec-4c7a-856e-cd29e1eedf8d.png)

**Comment by runkecheng** [comment]
leader服务指向主节点，可读写；follower服务指向从节点，只读。

**Comment by aliuq** [comment]
@runkecheng 那请问下 sample-mysql 呢

**Comment by runkecheng** [comment]
> @runkecheng 那请问下 sample-mysql 呢

sample-mysql 是一个无头服务，包含所有节点，你可以通过无头服务访问指定的节点，例如sample-mysql-0.sample-mysql.default.
