### ISSUE TITLE
Internal error/check (Not system error)

### ISSUE THREAD

**Issue by aliuq** [radondb/radondb-mysql-kubernetes#696]
安装使用的 `mysql_v1alpha1_mysqlcluster_mysql8.yaml`，添加用户用的是 `mysql_v1alpha1_mysqluser.yaml`，安装好之后使用 navicat 连接出现下面错误:

```bash
2013 _ Lost connection to MySQL server at 'waiting for initial communication packet', \
system error: 0 "Internal error/check (NOt system error)"
```

![image](https://user-images.githubusercontent.com/11707934/189906647-5f3854f9-4ff4-48e8-9229-541551156062.png)

![image](https://user-images.githubusercontent.com/11707934/189906772-47b002fb-97b4-4754-9e4d-12c7b5cfe288.png)

![image](https://user-images.githubusercontent.com/11707934/189907463-6ad1d353-4c43-4ff4-b353-f5fe2ac981da.png)

![image](https://user-images.githubusercontent.com/11707934/189907813-f5b87478-94a4-4980-a069-1a2dc03cbb49.png)

**Comment by runkecheng** [comment]
请问用户是否创建成功？

**Comment by aliuq** [comment]
@runkecheng 用户有创建成功

**Comment by acekingke** [comment]
确定一下navicat 与 mysql8.0.25 之间auth plugin 是否一致。

**Comment by aliuq** [comment]
@acekingke 一致，我是重装，之前是可以的，我怀疑是卸载的时候没卸载干净，官方能出个卸载教程吗？

**Comment by runkecheng** [comment]
> @acekingke 一致，我是重装，之前是可以的，我怀疑是卸载的时候没卸载干净，官方能出个卸载教程吗？

https://github.com/radondb/radondb-mysql-kubernetes/blob/main/docs/zh-cn/deploy_radondb-mysql_operator_on_k8s.md#%E5%8D%B8%E8%BD%BD
注意更新/卸载CRD即可。

**Comment by aliuq** [comment]
@runkecheng 之后遇到这个问题我再试试，这个问题出现几次了

**Comment by aliuq** [comment]
好长一段时间没用，这个问题还在……

**Comment by zhl003** [comment]
检查下 navicat 驱动对不对, 或者换dbeaver 试试
