### ISSUE TITLE
是否支持基于外部的nfs备份

### ISSUE THREAD

**Issue by yylstudy** [radondb/radondb-mysql-kubernetes#699]
operator version: v2.2.1
创建备份任务时，当nfsServerAddress配置的是k8s外部的地址，查看定时任务pod
![image](https://user-images.githubusercontent.com/26402953/190578745-4745b304-5fa1-478d-aa17-849be86a0306.png)
pod日志报错
![image](https://user-images.githubusercontent.com/26402953/190578845-b0a7225b-4b0a-412b-a433-22d51f503ed8.png)

请问下是否支持基于外部的nfs备份呢

**Comment by acekingke** [comment]
可以支持，你先确定
1. 网络是否可以访问。
2. pod 所在的node 是否安装nfs client

**Comment by yylstudy** [comment]
@acekingke 你好，是不是因为我定义的nfs服务端的存储是在/data/nfsdata下的，
![image](https://user-images.githubusercontent.com/26402953/190943021-a6b43a43-b9ac-41d0-8095-cadfe19d30cc.png)
但是operator未提供path的配置，我看了下job的yaml，默认是根目录
![image](https://user-images.githubusercontent.com/26402953/190942908-73a9e83f-e5b7-439f-8de0-4767b7e2ca69.png)
所以报错日志是挂载的时候创建/backup失败，没有写的权限，这个要怎么处理呢

**Comment by acekingke** [comment]
这个根目录和你服务端文件夹位置没有关系，请检查nfs server是否能对外服务

**Comment by yylstudy** [comment]
好的 谢谢
