### ISSUE TITLE
RadonDB MySQL Kubernetes是否支持arm架构

### ISSUE THREAD

**Issue by hhy62** [radondb/radondb-mysql-kubernetes#707]
RadonDB MySQL Kubernetes是否有官方的arm镜像或者制作镜像指导文档

**Comment by zhl003** [comment]
> RadonDB MySQL Kubernetes是否有官方的arm镜像或者制作镜像指导文档

你好，是支持的，需要自己编译arm相关的镜像

**Comment by hhy62** [comment]
> > RadonDB MySQL Kubernetes是否有官方的arm镜像或者制作镜像指导文档
> 
> 你好，是支持的，需要自己编译arm相关的镜像

我目前自己编的arm镜像percona/percona-server:5.7 启动报错，请帮忙看一下，具体信息如下：
![image](https://user-images.githubusercontent.com/108912016/194695510-b22dd344-d568-45ef-961b-f36cd0969fed.png)
**部署过程**
部署mysql-operator
helm upgrade --install  mysql-operator --create-namespace -n mysql mysql-operator-v2.2.1.tgz --set imagePrefix=192.168.0.35:8080
部署mysql
kubectl apply -f mysql_v1alpha1_mysqlcluster.yaml
部署过程在x86上已经调试过，使用官方镜像启动没有问题
**镜像制作Dockerfile**
FROM centos:8

LABEL org.opencontainers.image.authors="info@percona.com"

RUN set -ex; \
    groupdel input; \
    userdel systemd-coredump; \
    groupadd -g 1001 mysql; \
    useradd -u 1001 -r -g 1001 -s /sbin/nologin \
        -c "Default Application User" mysql

RUN set -ex; \
    export GNUPGHOME="$(mktemp -d)"; \
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*; \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*; \
    dnf -y install \
        gcc \
        gcc-c++ \
        kernel-devel \
        cmake \
        bzip2 \
        wget \
        openssl-devel \
        ncurses-devel \
        bison \
        readline-devel \
        libcurl-devel \
        curl \
        libtirpc-devel \
        dnf-utils \
        cracklib-dicts \
        which; \
    dnf clean all; \
    rm -rf /var/cache/dnf /var/cache/yum /var/lib/mysql; \ 
    curl -LO http://192.168.4.78:7079/rpcsvc-proto-1.4.1.tar.xz; \
    xz -d rpcsvc-proto-1.4.1.tar.xz; \
    tar -xvf rpcsvc-proto-1.4.1.tar; \
    cd rpcsvc-proto-1.4.1; \
    ./configure; \
    make  && make install; \
    cd ..; \
    curl -LO http://192.168.4.78:7079/zlib-1.2.11.tar.gz; \
    tar -xvf zlib-1.2.11.tar.gz; \
    cd zlib-1.2.11; \
    ./configure --prefix=/usr/local/zlib-1.2.11; \
    make && make install; \
    export LD_LIBRARY_PATH=/usr/local/zlib-1.2.11/lib:$LD_LIBRARY_PATH; \
    rm -rf /usr/local/boost/boost_1_59_0.tar.gz /rpcsvc-proto-1.4.1.tar.xz /zlib-1.2.11.tar.gz

RUN set -ex; \
    mkdir -p  /usr/local/boost; \
    wget https://jaist.dl.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.gz -O /usr/local/boost/boost_1_59_0.tar.gz; \
    curl -LO http://192.168.4.78:7079/percona-server.tar.gz; \
    tar -zxvf percona-server.tar.gz; \
    cd /percona-server; \
    cmake ./ -DCMAKE_INSTALL_PREFIX=/usr/          -DDEFAULT_CHARSET=utf8          -DDEFAULT_COLLATION=utf8_general_ci    -DDOWNLOAD_BOOST=1  -DWITH_BOOST=/usr/local/boost  -DZLIB_INCLUDE_DIR=/usr/local/zlib-1.2.11/include -DZLIB_LIBRARY=/usr/local/zlib-1.2.11/lib/; \
    sed -i '/INCLUDE(cmake\/abi_check.cmake)/d' CMakeLists.txt; \
    make; \
    make install; \
    dnf clean all; \
    rm -rf /var/cache/dnf /var/cache/yum /var/lib/mysql /percona-server.tar.gz /percona-server

COPY my.cnf /usr/my.cnf

RUN set -ex; \
    /usr/bin/install -m 0775 -o mysql -g root -d /var/lib/mysql /var/run/mysqld /docker-entrypoint-initdb.d; \
    mysqld --initialize --basedir=/usr --datadir=/var/lib/mysql --user=mysql; \
    /usr/support-files/mysql.server start; \
        find /etc/percona-server.cnf /etc/percona-server.conf.d /etc/my.cnf.d -name '*.cnf' -print0 \
                | xargs -0 grep -lZE '^(bind-address|log|user)' \
                | xargs -rt -0 sed -Ei 's/^(bind-address|log|user)/#&/'; \
        /usr/bin/install -m 0664 -o mysql -g root /dev/null /etc/sysconfig/mysql; \
        echo "LD_PRELOAD=/usr/lib64/libjemalloc.so.1" >> /etc/sysconfig/mysql; \
        echo "THP_SETTING=never" >> /etc/sysconfig/mysql; \
        ln -s /etc/my.cnf.d /etc/mysql; \
        chown -R mysql:root /usr/; \
        chmod -R ug+rwX /usr/

VOLUME ["/var/lib/mysql", "/var/log/mysql"]

COPY ps-entry.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

USER mysql
EXPOSE 3306
CMD ["mysqld"]

编译部分参考https://docs.percona.com/percona-server/5.7/installation/git-source-tree.html

使用指令 docker run -d   --name test   -e MYSQL_ROOT_PASSWORD=root   percona/percona-server:5.7.34 直接启动容器没有问题

**Comment by zhl003** [comment]
看起来 init-mysql 没有正确初始化，提供下这个容器的日志呢
