### ISSUE TITLE
sync_binlog、innodb-flush-log-at-trx-commit这两个参数不支持设置

### ISSUE THREAD

**Issue by yylstudy** [radondb/radondb-mysql-kubernetes#708]
你好，请问一下
k8s版本：1.23.6
operator版本：v2.2.1
在自定义sync_binlog、innodb-flush-log-at-trx-commit这两个参数时，发现无效
![image](https://user-images.githubusercontent.com/26402953/194700961-7e76fdfd-962d-4a4c-9d0c-32acbcb63583.png)
![image](https://user-images.githubusercontent.com/26402953/194700980-fc032e8e-3d96-453e-b377-a3e9bd836f2a.png)

这个是什么原因呢，谢谢

**Comment by acekingke** [comment]
你换成"innodb_flush_log_at_trx_commit" 试试？

**Comment by yylstudy** [comment]
你好，中划线和下划线这两个参数都试过了，不起作用，然后我看

**Comment by acekingke** [comment]
这两个参数是由xenon控制的，即使my.cnf 已经修改，xenon也会把他们修改回去。建议不要修改这两个参数。

**Comment by acekingke** [comment]
建议升级io存储，这两个参数改掉了，不太安全。不建议修改。
