### ISSUE TITLE
[BUG]🐛 rebuild the node but still inconsistent

### ISSUE THREAD

**Issue by zhl003** [radondb/radondb-mysql-kubernetes#709]
**Describe the problem**
In a cluster of two inconsistent slave nodes, one of them is rebuild. Even if the rebuild succeeds, the GTID of the node is still inconsistent

**To Reproduce**

1.

**Expected behavior**

**Environment:**

- RadonDB MySQL version:

**Comment by acekingke** [comment]
it has been fixed
