### ISSUE TITLE
unknown field "spec.mysqlOpts.image"

### ISSUE THREAD

**Issue by bocblca** [radondb/radondb-mysql-kubernetes#751]
kubectl apply -f mysql_v1alpha1_mysqlcluster.yaml
errinfo:
Error from server (BadRequest): error when creating "mysql_v1alpha1_mysqlcluster.yaml": MysqlCluster in version "v1alpha1" cannot be handled as a MysqlCluster: strict decoding error: unknown field "spec.mysqlOpts.image"

- RadonDB MySQL version:

**Comment by zhl003** [comment]
Did you upgrade CRD before deploy mysql cluster?
helm cannot manage CRD in upgrade situation ,  as it's said by official DOC :
"There is no support at this time for upgrading or deleting CRDs using Helm"
pls upgrade CRD manual :
```shell
kubectl apply -f https://raw.githubusercontent.com/radondb/radondb-mysql-kubernetes/v2.3.0/charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
```
and also apply [mysql.radondb.com_mysqlclusters.yaml](https://github.com/radondb/radondb-mysql-kubernetes/blob/v2.3.0/charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml)
and [mysql.radondb.com_mysqlusers.yaml](https://github.com/radondb/radondb-mysql-kubernetes/blob/v2.3.0/charts/mysql-operator/crds/mysql.radondb.com_mysqlusers.yaml)
