### ISSUE TITLE
Connection-Control Plugins插件怎么关闭啊

### ISSUE THREAD

**Issue by artugo** [radondb/radondb-mysql-kubernetes#752]
这个插件会导致unauthenticated user的连接数暴涨，导致连接数被占满，实在找不到地方关闭了
<img width="681" alt="image" src="https://user-images.githubusercontent.com/109275325/210696610-96511c55-36a7-423e-98c2-f207e812d32c.png">

我部署的是最新版的2.3.0，默认开启了Connection-Control Plugins插件，我把template里面mysql57_template.yaml,mysql80_template.yaml里面关于Connection-Control全都删了也不行，部署上去还是active状态
![image](https://user-images.githubusercontent.com/109275325/210696725-8344644d-d9fd-4499-b01c-a87fbb124ada.png)

主节点可以直接UNINSTALL，但是flower节点是只读节点没办法卸载这个插件

**Comment by artugo** [comment]
这个连接数会一直涨，把连接数全部占完
![image](https://user-images.githubusercontent.com/109275325/210707226-cfa940ba-c848-441a-9f14-2199345c9168.png)

**Comment by zhl003** [comment]
The connection_control plugin is enabled by default in version 2.3.0. You cannot uninstall it, but you can try setting the connection_control_failed_connections_threshold to "0" to prevent illegal connections from filling up connections.
```
kubectl patch mysql sample --type merge -p '{"spec":{"mysqlOpts":{"mysqlConf":{"connection_control_failed_connections_threshold":"0"}}}}'
```

**Comment by zhl003** [comment]
> 这个连接数会一直涨，把连接数全部占完 ![image](https://user-images.githubusercontent.com/109275325/210707226-cfa940ba-c848-441a-9f14-2199345c9168.png)

By the way, why are there so many illegal connections in your database? Is it because the app has the wrong password set
