### ISSUE TITLE
How to quickly and easily repair master-slave delay

### ISSUE THREAD

**Issue by bongmu** [radondb/radondb-mysql-kubernetes#767]
![image](https://user-images.githubusercontent.com/33013978/224191975-b47cb18d-d668-4378-bd50-633e713323ef.png)

I deployed replicas 2 in the cluster. The MysqlCluster,slave synchronization process is normal, but the delay is more than 1 day, and it continues to grow.
How should I fix it? can I dump sql on master and then import and change master on slave? Or is there any other better way?

**Comment by acekingke** [comment]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/7586502/224203808-9cf6e4d6-b0a3-4f1c-88e5-709c45ec0232.png">
There are some long time transactions having not been commited, or some locks block the transactions. Please check them and fix them.

**Comment by acekingke** [comment]
After you fix the problems, you can rebuild the pod.

**Comment by bongmu** [comment]
Thank you for your reply.
There is no transaction on the slave, just because the synchronization process was interrupted for some reason the day before yesterday and did not deal with it in time.


On master, because the policy of keeping binlog files for one day was set, it was speculated that part of the data might be lost because the binlog could not be read, resulting in a 1062 error. But I skipped the error and brought the synchronization process back to normal. It turns out that although the synchronization process is normal, some data is indeed lost.

I want to synchronize all data to ensure that slave data is not lost as much as possible, what should be done, or what better suggestions

**Comment by bongmu** [comment]
I tried to restart slave pod, but the data was still lost.

**Comment by acekingke** [comment]
rebuild the slave pod, it will restore from master pod by using xtrabackup.
