### ISSUE TITLE
the slave Slave_IO_Running not Yes

### ISSUE THREAD

**Issue by bongmu** [radondb/radondb-mysql-kubernetes#768]
![image](https://user-images.githubusercontent.com/33013978/224225781-ae19b82a-f584-4164-8ebf-6ca82038ebb0.png)

What should I do

**Comment by bongmu** [comment]
Got fatal error 1236 from master when reading data from binary log: 'The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID sets and the missing purged transactions are too long to print in this message. For more information, please see the master's error log or the manual for GTID_SUBTRACT.'

**Comment by acekingke** [comment]
the xenon component will always set slave to readonly, so if you want recover data, use rebuild label,ref  the document
