### ISSUE TITLE
如何修改运行中的mysql参数

### ISSUE THREAD

**Issue by crazychengmm** [radondb/radondb-mysql-kubernetes#773]
## General Question
您好，想请教下，如何在运行的实例上面修改mysql的配置参数，有些是需要重启才能生效，有些是无需重启实例就能生效，
能否有一个操作手册，或者恢复下如何做

另外有三个建议：

1. 官方的介绍视频都404了

![image](https://user-images.githubusercontent.com/23517542/227161405-de71939a-3818-4a2a-9206-e586289648ed.png)

2. https证书过期了 
![image](https://user-images.githubusercontent.com/23517542/227161545-6e5ba5db-2095-4ee9-b260-61238bbfc053.png)

3. 产品优势，如果能更具体的说明下就更好了，本人才接触这个社区的产品，绝对在云原生的体系下，这个自建RDS非常优秀，打算内部推广，如果把产品优势写的更明确具体些，相信用户会原来越多，祝愿更好未来 
![image](https://user-images.githubusercontent.com/23517542/227162293-b48421ae-ba14-4712-8133-eb785ee2953b.png)

**Comment by crazychengmm** [comment]
> 

感谢回复！
参数有些是可以不重启实例生效的，有些需要重启实例生效，这个是自己会判断参数吗？

**Comment by zhl003** [comment]
现在全部是重启实例生效

**Comment by crazychengmm** [comment]
好的，谢谢

**Comment by nobu121** [comment]
修改参数后出发滚动更新，但是更新完成后发现所有节点都变成follower了，这是为什么呢？ @zhl003
