### ISSUE TITLE
数据库备份到S3的数量

### ISSUE THREAD

**Issue by crazychengmm** [radondb/radondb-mysql-kubernetes#775]
## General Question
备份到S3，如果S3有空间限制，备份的是否可以设置备份几代？

好像没有这个参数配置，目前是不支持吗

**Comment by zhl003** [comment]
是的 ,目前没支持备份片的生命周期管理, 可以在s3服务端设置bucket的生命周期来实现你需要的能力

**Comment by crazychengmm** [comment]
感觉是不是把备份与旧备份删除搞到一块更好点，属于一个事务里面。
还有就是备份的话，定义成了crd来管理，是不是把对象存储里面的文件也包含在crd里面，我删除了备份，但是存储里面的文件还在。
do 备份
if 成功:
   save (备份成功后存储相关信息到etcd，如：对象存储备份)
   delete old (删除旧备份)
else：
   notive (备份失败)

**Comment by Littlehhao** [comment]
crd 里面有这个参数backupScheduleJobsHistoryLimit ， 但是没用
