### ISSUE TITLE
如何正确的重启radondb集群？

### ISSUE THREAD

**Issue by crazychengmm** [radondb/radondb-mysql-kubernetes#776]
## General Question
如上面的问题，重启statefulset的话，一般都是删除pod，目前重启整个集群的话，
怎么样的顺序更合理点？

能否说明具体点

**Comment by zhl003** [comment]
重启集群你可以直接 `scale mysql xxx --replica=0` 然后`scale mysql xxx --replica=3` 这样达到重启数据库集群的目的
