### ISSUE TITLE
When create MysqlCluster with sample yaml, failed to mount /etc/localtime on rancher-desktop

### ISSUE THREAD

**Issue by zheng11581** [radondb/radondb-mysql-kubernetes#777]
**Describe the problem**

When create MysqlCluster with sample yaml, failed to mount /etc/localtime on rancher-desktop

**To Reproduce**

I start a one-node kubernets cluster with rancher-desktop. Then deploy the mysql-operator from local.
When create MysqlCluster with sample yaml, failed to mount /etc/localtime on rancher-desktop

1. install rancher desktop
2. start a cluster v1.23.5
3. Download the code
4. Deploy the operator
5. Apply the config/samples/mysql_v1alpha1_mysqlcluster.yaml

**Expected behavior**

The MySQL cluster should be setup, but it not
**Environment:**

- RadonDB MySQL version: 5.7.34

**Comment by zheng11581** [comment]
I have localtime file the node host.
![Uploading image.png…]()

**Comment by acekingke** [comment]
The image cannot  be seen.
