### ISSUE TITLE
mysql_v1alpha1_mysqluser创建用户资源自定义用户名不生效，只支持super-user吗？

### ISSUE THREAD

**Issue by secondwifelikemytalent** [radondb/radondb-mysql-kubernetes#779]
创建了集群，默认用户可以正常连接，为什么自定义用户名创建新用户？ 
![image](https://user-images.githubusercontent.com/45771250/232717876-31702973-12de-4fea-8730-0d0eddd894f1.png)
![image](https://user-images.githubusercontent.com/45771250/232718038-7f67418d-5481-4c47-a49e-3794ab261dc7.png)

**Comment by zhl003** [comment]
`kubectl describe  mysqlusers.mysql.radondb.com  tom ` 看下里面有没有报错信息

**Comment by lx3xun** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/6147862/232973264-ab3b4fb0-573f-4acc-b75a-1e7d6cd6adea.png">
我也出现这个问题

**Comment by zhl003** [comment]
> <img alt="image" width="860" src="https://user-images.githubusercontent.com/6147862/232973264-ab3b4fb0-573f-4acc-b75a-1e7d6cd6adea.png">
> 
> 我也出现这个问题

kubectl describe  mysqlusers.mysql.radondb.com `super-user`

**Comment by lx3xun** [comment]
提示以下错误，但我就是按教程一步一步来的啊
<img width="738" alt="image" src="https://user-images.githubusercontent.com/6147862/233325824-2b041312-917c-4e03-9b82-9b196e96c688.png">

**Comment by acekingke** [comment]
集群sample是否存在？

理想三旬 ***@***.***> 于2023年4月20日周四 17:39写道：

**Comment by OneBlueCat** [comment]
我配置的时候上面的密码不是对应用户名而是对应用户类型的，即
super-user: UmFkbXXXXX
normal-user:  UmFkbXXXXX

**Comment by acekingke** [comment]
base64 编码用 `echo -n xxx |base64 ` 这种， 不要忘记echo 后面添加 -n
