### ISSUE TITLE
prometheus-operator监测不到集群

### ISSUE THREAD

**Issue by secondwifelikemytalent** [radondb/radondb-mysql-kubernetes#783]
操作系统信息
虚拟机，Centos7.9 /2C/4G
节点数量
master*3/node*2

Kubernetes版本信息
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17"}

容器运行时
Version:           23.0.1
API version:       1.42
Go version:        go1.19.5

问题：新创建serviceMonitor关联mysql-cluster的service，prometheus不能检测到serviceMonitor
yaml文件如下：
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-cluster
  namespace: monitoring
  labels:
    app: mysql-cluster
spec:
  jobLabel: k8s-mysql
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      scrapeTimeout: 3s
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: mysql.radondb.com
      app.kubernetes.io/name: mysql
  namespaceSelector:
    any: true
麻烦帮忙看哪里配置的不正确，应该怎么改。谢谢

**Comment by acekingke** [comment]
这个service monitor 的namespace 是否与mysql集群不一致？

**Comment by secondwifelikemytalent** [comment]
> 这个service monitor 的namespace 是否与mysql集群不一致？ 再就是yaml文件的mertic 是否开启？

sample-metrics可以获取到数据，集群安装在mysql命名空间，所以我想写一个和Prometheus同命名空间的servicemonitor关联metrics的service，但是prometheus一直都检测不到，不知道哪里写的不对。

**Comment by acekingke** [comment]
@secondwifelikemytalent  是什么原因呢？
