### ISSUE TITLE
按照文档部署完集群，xenonctl cluster status mysql 状态未知，开启监控后notrunning

### ISSUE THREAD

**Issue by Sjhu1024** [radondb/radondb-mysql-kubernetes#788]
## General Question

按照文档部署完集群，xenonctl cluster status mysql 状态未知，开启监控后notrunning

![image](https://github.com/radondb/radondb-mysql-kubernetes/assets/25522750/2f3fa833-5db4-456c-a680-65c327b7d345)

**Comment by acekingke** [comment]
at the version of mysql for k8s, xenon monitor is not need, so it do not
running, when you want monitor, please install prometheus  and open the
metric flag in yaml file.

github-actions[bot] ***@***.***> 于2023年5月19日周五 09:59写道：
