### ISSUE TITLE
open /etc/xenon/xenon.json: permission denied

### ISSUE THREAD

**Issue by liujing1087** [radondb/radondb-mysql-kubernetes#792]
**Describe the problem**

集群初始失败，xenon报错open /etc/xenon/xenon.json: permission denied

xenon:[{Tag:v1.1.4-34-gbae9e0d Time:2023/05/09 03:26:25 Git:bae9e0d GoVersion:go1.18.8 Platform:linux arm64}]
 2023/06/06 16:35:02.447404 xenon.go:52:         [PANIC]        xenon.loadconfig.error[open /etc/xenon/xenon.json: permission denied]
panic:   [PANIC]        xenon.loadconfig.error[open /etc/xenon/xenon.json: permission denied]

goroutine 1 [running]:
xbase/xlog.(*Log).Panic(0x40002062a0, {0x468b3b?, 0x45ee13?}, {0x40000ffbf0?, 0x40000ffbe0?, 0x1?})
        /go/src/github.com/radondb/xenon/src/xbase/xlog/xlog.go:164 +0xd0
main.main()
        /go/src/github.com/radondb/xenon/src/xenon/xenon.go:52 +0x338

**Environment:**

- Kubernetes version: v1.16.14
- Helm version: v3.12.0
- RadonDB MySQL version:  v2.3.0
- CPU arch: arm64

**Comment by acekingke** [comment]
check you images is correct ?

**Comment by Littlehhao** [comment]
这个问题我也遇到了，请问解决了吗？

是从docker pull --platform=linux/arm64 radondb/xenon:v2.3.0 下载的镜像
