### ISSUE TITLE
3.0.1版本bug

### ISSUE THREAD

**Issue by a1105124657** [radondb/radondb-mysql-kubernetes#806]
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "radondb-mysql-certificate" namespace: "default" from "": no matches for kind "Certificate" in version "cert-manager.io/v1"
前几天版本并未出现，重新安装新的出现这个Bug，希望提供这个yaml出来

**Comment by acekingke** [comment]
你是用helm 安装的吗？

**Comment by nanjiyueguang** [comment]
我也遇到类似的错误，请问解决了吗 @a1105124657

**Comment by acekingke** [comment]
1. 要么安装certmanger
2. 要么使用如下方式安装:
```
helm install demo charts/mysql-operator   --set webhook.certManager.enable=false
```
建议安装3.0.0

**Comment by a1105124657** [comment]
> 你是用helm安装的吗？

是的，不过已经解决了，低版本的yaml配置加上3.0.0镜像

**Comment by a1105124657** [comment]
> 我也遇到类似的错误，请解决了吗@a1105124657
helm安装低版本的，但是因为yaml里面镜像版本标志是latest，所以也等于安装最新了
