### ISSUE TITLE
NFSscheduleBackup

### ISSUE THREAD

**Issue by twobunches** [radondb/radondb-mysql-kubernetes#814]
## General Question

backup的crd中有backupRetention和jobhistoryLimit这两个字段，nfs定时备份配置之后，备份能够执行，但是留存策略和jobhistoryLimit似乎是不生效的，我在代码中也没有看到关于留存相关的逻辑，这是否需要自己去实现？因为不可能让备份无限增长

我的backup.yaml如下：
apiVersion: mysql.radondb.com/v1beta1
kind: Backup
metadata:
  name: backup-cronjob
spec:
  backupops:
    nfs:
      volume:
        path: /
        server: "192.101.93.252"
  clusterName: cluster
  method: xtrabackup
  schedule:
    backupRetention: 1
    jobhistoryLimit: 1
    cronExpression: "30 15 * * *"
    type: nfs

**Comment by acekingke** [comment]
用户可以自己写脚本去删除备份，或者手动删除备份，用代码删除备份，比较危险，而且责任难以追究。

github-actions[bot] ***@***.***> 于2023年8月16日周三 16:03写道：

**Comment by acekingke** [comment]
不行，官方的 k8s 例子有错误， 把其中 service 换成 DNS 无法运行，您可以尝试一下。
