### ISSUE TITLE
mysql第三个pod启动时报错[ERROR] [MY-011825] [Xtrabackup] cannot open ./xtrabackup_checkpoints

### ISSUE THREAD

**Issue by liarby** [radondb/radondb-mysql-kubernetes#822]
operator image:2.3.0
mysql image：percona/percona-server:8.0.33

**报错日志如下：**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    18    0    18    0     0    204      0 --:--:-- --:--:-- --:--:--   204
xb_stream_read_chunk(): wrong chunk magic at offset 0x0.
exit code: 1
1.6954081598559616e+09	INFO	sidecar	mysql is not initialized, use shell script copying plugin.cnf
1.6954081598562207e+09	INFO	sidecar	xtrabackup prepare apply-log only
2023-09-22T18:42:39.874633-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized client arguments: --use-memory=3072M --prepare=1 --apply-log-only=1 --target-dir=/var/lib/mysql 
xtrabackup version 8.0.29-22 based on MySQL server 8.0.29 Linux (x86_64) (revision id: c31e7ddcce3)
2023-09-22T18:42:39.874710-00:00 0 [Note] [MY-011825] [Xtrabackup] cd to /var/lib/mysql/
2023-09-22T18:42:39.874729-00:00 0 [ERROR] [MY-011825] [Xtrabackup] cannot open ./xtrabackup_checkpoints
2023-09-22T18:42:39.874736-00:00 0 [ERROR] [MY-011825] [Xtrabackup] failed to read metadata from './xtrabackup_checkpoints'
1.6954081598759935e+09	ERROR	sidecar	init command failed	{"error": "failed to execute Clone Restore : failed to xtrabackup prepare apply-log-only : exit status 1"}
github.com/radondb/radondb-mysql-kubernetes/sidecar.NewInitCommand.func1
	/workspace/sidecar/init.go:53
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	/workspace/cmd/sidecar/main.go:96
runtime.main
	/usr/local/go/src/runtime/proc.go:255

**Comment by acekingke** [comment]
请做如下动作：
1. 检查网络是否可以连通。
2. 检查存储空间是否足够。
从日志来看， 这里xtrackup并没有成功从某个节点获取数据。日志并不完整，不清楚是从哪里获取，但是可以判断是在新节点做克隆的是出错了

**Comment by liarby** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件我已收到，尽快给您回复。

**Comment by liarby** [comment]
> 请做如下动作：
> 
> 1. 检查网络是否可以连通。
> 2. 检查存储空间是否足够。
>    从日志来看， 这里xtrackup并没有成功从某个节点获取数据。日志并不完整，不清楚是从哪里获取，但是可以判断是在新节点做克隆的是出错了

报错日志是init-sidecar里面的
忘了说一下我这边的操作，两种情况：
①将MySQL镜像由原来的8.0.25升级到8.0.33的过程中发现pod-2、pod-1都能正常启动，pod-0无法启动，报错如上；
②直接将镜像设置为8.0.33新建一个3节点集群，第一个pod正常、第二个pod正常，第三个pod无法启动，报错如上；

**Comment by acekingke** [comment]
operator 是什么版本？

**Comment by liarby** [comment]
> operator image:2.3.0
> mysql image：percona/percona-server:8.0.33
> sidecar image：v2.3.0

**Comment by liarby** [comment]
> operator 是什么版本？
咱们的镜像打包好像有点问题，10个月前的sidecar版本和7个月前的sidecar版本都是v2.3.0，但是xtrabackup版本不一样

另外是不是percona-server的版本要跟xtrabackup的版本保持一致才行

**Comment by acekingke** [comment]
对，必须一致。

**Comment by liarby** [comment]
> 对，必须一致。

好的，谢谢
