### ISSUE TITLE
Backup with S3 start failed in kubesphere,need help!

### ISSUE THREAD

**Issue by iwannamaybe** [radondb/radondb-mysql-kubernetes#823]
##  According to the doc,exec "kubectl apply -f mysql_v1alpha1_backup.yaml" with error:
Error from server: error when creating "mysql_v1alpha1_backup.yaml": conversion webhook for mysql.radondb.com/v1alpha1, Kind=Backup failed: parsing time "" as "2006-01-02 15:04:05": cannot parse "" as "2006"

# kubelet version
v1.22.12
# docker version
20.10.8
# radondb-mysql-operator
v3.0.1

# operator's container log
ts=2023-09-25T20:10:02.481015987Z level=error logger=conversion-webhook msg="failed to convert" request=81d9b5ef-d866-4ca4-84e6-87f72b6604e7 error="parsing time \"\" as \"2006-01-02 15:04:05\": cannot parse \"\" as \"2006\"" stacktrace="sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*Webhook).ServeHTTP\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/webhook/conversion/conversion.go:76\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/promhttp/instrument_server.go:40\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2047\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/promhttp/instrument_server.go:117\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2047\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/promhttp/instrument_server.go:84\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2047\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2425\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2879\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1930"

# mysql_v1alpha1_mysqlcluster_mysql8.yaml
apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlCluster
metadata:
  name: ifornew
spec:
  replicas: 3
  mysqlVersion: "8.0"
  backupSecretName: ifornew-backup-secret

# mysql_v1alpha1_backup.yaml
apiVersion: mysql.radondb.com/v1alpha1
kind: Backup
metadata:
  name: backup-ifornew
spec:
  hostName: ifornew-mysql-0
  clusterName: ifornew

**Comment by acekingke** [comment]
v1alpha1 is abadoned, please use v1beta1 api.

**Comment by iwannamaybe** [comment]
ok,thanks,i'll have a try with v1beta1.

**Comment by ZouYuan1994** [comment]
Did it work? I'm having the same issue
