### ISSUE TITLE
集群出现问题后，与主节点同步出现问题

### ISSUE THREAD

**Issue by crazychengmm** [radondb/radondb-mysql-kubernetes#826]
**Describe the problem**

**To Reproduce**

![image](https://github.com/radondb/radondb-mysql-kubernetes/assets/23517542/7811353a-09a8-4449-9eca-5908e37b3818)

**Expected behavior**

**Environment:**

- RadonDB MySQL version: 2.3.0

**Comment by crazychengmm** [comment]
我如何解决这个问题，按照官方的操作手册，重建备节点，还是不行
![image](https://github.com/radondb/radondb-mysql-kubernetes/assets/23517542/82666e2b-fabb-4e3f-9f53-6e7dbc68edd1)
角色变成 LEARNER，持续了很久的时间

**Comment by crazychengmm** [comment]
尝试把主节点备份到s3上面，然后重建备节点，还是失败了，下面是报错
![image](https://github.com/radondb/radondb-mysql-kubernetes/assets/23517542/c06b8b8b-69b8-4f88-9623-9397df39a9cb)

**Comment by acekingke** [comment]
使用命令 `kubectl label pod mysql-local-mysql-0 rebuild=1`  mysql 容器化的官方手册操作手册没有你这种操作方法。

**Comment by crazychengmm** [comment]
> 使用命令 `kubectl label pod mysql-local-mysql-0 rebuild=1` mysql 容器化的官方手册操作手册没有你这种操作方法。

http://www.radondb.com/posts/210825_%E9%AB%98%E5%8F%AF%E7%94%A8-_-xenon-%E5%AE%9E%E7%8E%B0-mysql-%E9%AB%98%E5%8F%AF%E7%94%A8%E6%9E%B6%E6%9E%84-%E5%B8%B8%E7%94%A8%E6%93%8D%E4%BD%9C%E7%AF%87/
大佬 我看的是这个文档，您能告诉下我正确的是哪个文档吗？
感谢

**Comment by acekingke** [comment]
这个是1.0.0 的文档，现在已经废弃了

**Comment by crazychengmm** [comment]
> 这个是1.0.0 的文档，现在已经废弃了

可以发给我最新的文档地址吗，感谢，还是说代码里面的md文件就是了

**Comment by acekingke** [comment]
代码中的md文档就是的
