### ISSUE TITLE
can't read /etc/mysql/conf.d/init.sql: Permission denied

### ISSUE THREAD

**Issue by Littlehhao** [radondb/radondb-mysql-kubernetes#833]
arm64 环境下 radondb-mysql-kubernetes-2.3.0版本下mysql5.7  mysql-cluster启动报错

<img width="1665" alt="image" src="https://github.com/radondb/radondb-mysql-kubernetes/assets/43262022/1259478c-ce6a-428a-a40f-becc3ad8f2c6">

我没找到init.sql 怎么挂载进去的，不知道如何改权限

**Comment by acekingke** [comment]
请检查sidecar， operator，的镜像版本是否一致。

**Comment by Littlehhao** [comment]
docker pull radondb/mysql57-sidecar:v2.3.0-arm64
docker pull radondb/mysql-operator:v2.3.0-arm64

我确定我拉的都是2.3.0 的镜像。

我尝试修改了
<img width="930" alt="image" src="https://github.com/radondb/radondb-mysql-kubernetes/assets/43262022/a8d1e7c5-d19f-4d33-9bda-5044210e17a7">
这个写入的权限为0777，但是还是不行。
我不知道为什么在arm64环境一直没有权限读取init.sql，在amd64环境是好的

**Comment by acekingke** [comment]
按道理没有问题的。
